version: 2

jobs:
  build: 
    docker: 
      - image: circleci/node:12.18
        environment:
            DB_PGSQL_HOST: localhost
            DB_PGSQL_PORT: 5432
            DB_PGSQL_DATABASE: test
    steps:
      - checkout

      - run: cp .env.test .env
      - run: cd api && npm ci
      - run: cd api && npm test