version: 2

jobs:
  build: 
    docker: 
      - image: circleci/node:12.18
        environment: 
            DB_PGSQL_HOST: localhost
            DB_PGSQL_PORT: 5432
            DB_PGSQL_DATABASE: test
             services:
    postgres:
      - image: postgres:latest 
        env:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: example
            POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: npm install

      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Create database
          command: npm run db:reset:test
      - run: cd api && npm ci
      - run: cd api && npm test